### ISSUE TITLE
I cant figure it out how to use this..

### ISSUE THREAD

**Issue by andlo** [vince-fugnitto/theia-cpp-branding#6]
Sorry - I am not that good. But I would realy like to brand a theia app I am making for Mycroft.AI. But I cant figure out how to use this in a build to get a way to brand the TheiaIDE.
Any clues or descriptions on how to add a module to a build of theia ?

**Comment by vince-fugnitto** [comment]
Sorry @andlo for some reason I was not getting notified about activity in the repository.
Are you still struggling?

**Comment by andlo** [comment]
hi @vince-fugnitto - I am not struggling, but I didnt manage to get it to work. So I stopped trying. If you hve some cues hints or description on how to use branding I would be very glad. But I understand there are much other stuff to attend to and branding is moe or less just topping on some great work :) 

I have made a extension to mycroft - a open voice assistant like Alexa and google home, and use Theia as an on device devolopment enviorement. Pritty cool to edit nd make skills directly on the device and make it easy fo newcomers to get started. And putting some nice branding into it would make it look great :)
I am not a programmer, but making small apps (skills) for a vice assistant is fun, but it were difficult to get started and that is the hurdle a on device IDE would help so others dont face same challenge.

**Comment by vince-fugnitto** [comment]
@andlo that's a very cool project! I'm glad you thought of Theia :)
This repo is mainly an example of how to easily create an extension to brand parts of the application, namely the `menu` and the `main` icon in the main panel when no widgets/editors are present.

If ever you'd like to create your own, you can simply use the example and update the assets.
Then I'd assume you'd need to publish your extension to `npm`. If you already have an extension for `mycroft` you can simply add the functionality I have in this extension.

**Comment by andlo** [comment]
thanks - no I dont have an extension for mycroft - I just make a theia application acording to this https://theia-ide.org/docs/composing_applications and pack it into  a package that can install on the mycroft device and have it configure and set up for the user. So what I need to figure out is how to add your branding extension (and change the assets) and make that build when I build the application. 
Iwe come a long way learning yarn, npm and stuff around that to get it working - like I have to get it to build on a lowspec raspberrypi but it does build and run great. But how to add brandingI hassnt yet figuered out. 
Something with cloning the repo and add some thing to the package.json, but it dosnt do the trick :(

**Comment by vince-fugnitto** [comment]
@andlo 
The idea would be to create your own extension (or fork of this one), and update the [images](https://github.com/vince-fugnitto/theia-cpp-branding/tree/master/assets/icons) to your own. You can then publish the extension to `npm` or any other way you'd like to bundle it. This will allow you to reference it like you already do for let's say `@theia/core` in your own IDE.

In this repo you can see that the `branding` extension is present and the `browser-app` and `electron-app` both refer to it. This allows these example applications to make use of the `branding` extension.

**Comment by andlo** [comment]
ok ill try again :)
